# Copyright 2018 Google, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Builds the static Go image to execute in a Kubernetes job

# Stage 0: Build the executor binary and get credential helpers
FROM golang:1.13
ARG GOARCH=arm
WORKDIR /go/src/github.com/GoogleContainerTools/kaniko
# Get GCR credential helper
RUN export GOPATH=/usr/local; go get -ldflags "-linkmode=external "-extldflags=-static"" -u github.com/GoogleCloudPlatform/docker-credential-gcr; export GOPATH=/go;
RUN docker-credential-gcr configure-docker
# Get Amazon ECR credential helper
RUN export GOPATH=/usr/local; go get -ldflags "-linkmode=external "-extldflags=-static"" -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login; export GOPATH=/go

COPY . .
RUN sed -i 's/supported.", math.MaxUint32/supported.", uint32\(math.MaxUint32\)/g' pkg/util/fs_util.go
RUN make GOARCH=${GOARCH} && make out/warmer

# Stage 1: Get the busybox shell
FROM busybox
RUN echo 'got busybox'

FROM scratch
COPY --from=0 /go/src/github.com/GoogleContainerTools/kaniko/out/* /kaniko/
COPY --from=0 /usr/local/bin/docker-credential-gcr /kaniko/docker-credential-gcr
COPY --from=0 /usr/local/bin/docker-credential-ecr-login /kaniko/docker-credential-ecr-login
COPY --from=1 /bin/ /busybox/
# Declare /busybox as a volume to get it automatically whitelisted
VOLUME /busybox
COPY files/ca-certificates.crt /kaniko/ssl/certs/
COPY --from=0 /root/.docker/config.json /kaniko/.docker/config.json
ENV HOME /root
ENV USER /root
RUN ln -s /busybox /bin
ENV PATH /usr/local/bin:/kaniko:/busybox:/bin
ENV SSL_CERT_DIR=/kaniko/ssl/certs
ENV DOCKER_CONFIG /kaniko/.docker/
ENV DOCKER_CREDENTIAL_GCR_CONFIG /kaniko/.config/gcloud/docker_credential_gcr_config.json
RUN ["docker-credential-gcr", "config", "--token-source=env"]
ENTRYPOINT ["/kaniko/executor"]
